# Generated by Django 3.2.5 on 2023-05-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('order_date', models.DateField(null=True)),
                ('ship_date', models.DateField(null=True)),
                ('customer_id', models.TextField(null=True)),
                ('customer_name', models.TextField(null=True)),
                ('segent', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('sub_category', models.TextField(null=True)),
                ('product_name', models.TextField(null=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
