# Generated by Django 3.2.5 on 2023-05-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='segent',
            new_name='segment',
        ),
    ]
